"""initial schema

Revision ID: 39626a238bda
Revises: 
Create Date: 2026-09-05 22:56:55.065694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39626a238bda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_log_username'), ['username'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_single', sa.Boolean(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_batch_key'), ['batch_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_owner_id'), ['owner_id'], unique=False)

    op.create_table('calibration_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('preset_name', sa.String(length=128), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('x_left_0deg', sa.Integer(), nullable=False),
    sa.Column('x_right_360deg', sa.Integer(), nullable=False),
    sa.Column('y_top_plot', sa.Integer(), nullable=False),
    sa.Column('y_bottom_plot', sa.Integer(), nullable=False),
    sa.Column('saved_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('example_prpd_filename', sa.String(length=255), nullable=True),
    sa.Column('example_tf_filename', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'preset_name', name='uq_preset_owner_name')
    )
    with op.batch_alter_table('calibration_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_presets_image_height'), ['image_height'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_presets_image_width'), ['image_width'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_presets_owner_id'), ['owner_id'], unique=False)

    op.create_table('trained_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=96), nullable=True),
    sa.Column('class_names', sa.Text(), nullable=True),
    sa.Column('pd_sources', sa.Text(), nullable=True),
    sa.Column('severity_groups', sa.Text(), nullable=True),
    sa.Column('train_count', sa.Integer(), nullable=False),
    sa.Column('test_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('dataset_detail', sa.Text(), nullable=True),
    sa.Column('max_epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('backbone', sa.String(length=24), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('val_accuracy', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('engine_used', sa.String(length=16), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('thresholds_snapshot', sa.Text(), nullable=True),
    sa.Column('data_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_model_owner_name')
    )
    with op.batch_alter_table('trained_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trained_models_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trained_models_status'), ['status'], unique=False)

    op.create_table('user_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topclass_threshold', sa.Float(), nullable=True),
    sa.Column('joint_dual_threshold', sa.Float(), nullable=True),
    sa.Column('strong_rule_threshold', sa.Float(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('internal_high_confidence', sa.Float(), nullable=True),
    sa.Column('gap_time_high_ms', sa.Float(), nullable=True),
    sa.Column('gap_time_moderate_ms', sa.Float(), nullable=True),
    sa.Column('cycle_time_ms', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_thresholds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_thresholds_user_id'), ['user_id'], unique=True)

    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision_mode', sa.String(length=24), nullable=False),
    sa.Column('analysis_run', sa.Boolean(), nullable=False),
    sa.Column('inference_engine', sa.String(length=16), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('defect_id', sa.String(length=64), nullable=True),
    sa.Column('defect_name', sa.String(length=255), nullable=True),
    sa.Column('case_folder', sa.String(length=255), nullable=True),
    sa.Column('case_base_name', sa.String(length=255), nullable=False),
    sa.Column('prpd_filename', sa.String(length=255), nullable=True),
    sa.Column('tf_filename', sa.String(length=255), nullable=True),
    sa.Column('source_prpd_path', sa.Text(), nullable=True),
    sa.Column('source_tf_path', sa.Text(), nullable=True),
    sa.Column('ai_mode', sa.String(length=32), nullable=True),
    sa.Column('ai_input_mode', sa.String(length=32), nullable=True),
    sa.Column('ai_model_used', sa.String(length=128), nullable=True),
    sa.Column('ai_model_path', sa.Text(), nullable=True),
    sa.Column('ai_top_class', sa.String(length=32), nullable=True),
    sa.Column('ai_top_score_percent', sa.Float(), nullable=True),
    sa.Column('ai_final_result', sa.String(length=64), nullable=True),
    sa.Column('ai_final_score_percent', sa.Float(), nullable=True),
    sa.Column('ai_status', sa.String(length=64), nullable=True),
    sa.Column('ai_high_conf_count', sa.Integer(), nullable=True),
    sa.Column('ai_non_identified_percent', sa.Float(), nullable=True),
    sa.Column('ai_decision_rule', sa.Text(), nullable=True),
    sa.Column('ai_threshold_percent', sa.Float(), nullable=True),
    sa.Column('ai_confidence_corona', sa.Float(), nullable=True),
    sa.Column('ai_confidence_surface', sa.Float(), nullable=True),
    sa.Column('ai_confidence_internal', sa.Float(), nullable=True),
    sa.Column('ai_confidence_json', sa.Text(), nullable=True),
    sa.Column('class_scheme', sa.Text(), nullable=True),
    sa.Column('pd_rule_class', sa.String(length=64), nullable=True),
    sa.Column('pd_selection_rule', sa.Text(), nullable=True),
    sa.Column('is_strong_pd_rule', sa.Boolean(), nullable=True),
    sa.Column('suggested_pd_source_type', sa.String(length=64), nullable=True),
    sa.Column('confirmed_pd_source_type', sa.String(length=64), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('default_size_match', sa.Boolean(), nullable=True),
    sa.Column('calibration_mode', sa.String(length=64), nullable=True),
    sa.Column('auto_calibration_status', sa.String(length=64), nullable=True),
    sa.Column('calibration_source', sa.String(length=64), nullable=True),
    sa.Column('calibration_preset_loaded', sa.Boolean(), nullable=True),
    sa.Column('calibration_preset_path', sa.Text(), nullable=True),
    sa.Column('x_left_0deg', sa.Integer(), nullable=True),
    sa.Column('x_right_360deg', sa.Integer(), nullable=True),
    sa.Column('y_top_plot', sa.Integer(), nullable=True),
    sa.Column('y_bottom_plot', sa.Integer(), nullable=True),
    sa.Column('auto_gap_status', sa.String(length=255), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_name', sa.String(length=128), nullable=True),
    sa.Column('reviewer_role', sa.String(length=32), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('left_line_pixel', sa.Float(), nullable=True),
    sa.Column('right_line_pixel', sa.Float(), nullable=True),
    sa.Column('left_phase_deg', sa.Float(), nullable=True),
    sa.Column('right_phase_deg', sa.Float(), nullable=True),
    sa.Column('gap_angle_deg', sa.Float(), nullable=True),
    sa.Column('gap_time_ms', sa.Float(), nullable=True),
    sa.Column('gap_time_band', sa.String(length=32), nullable=True),
    sa.Column('severity_by_gap_time', sa.String(length=32), nullable=True),
    sa.Column('gap_measurement_status', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('detected_case', sa.String(length=64), nullable=True),
    sa.Column('positive_x_range_pixel', sa.String(length=64), nullable=True),
    sa.Column('negative_x_range_pixel', sa.String(length=64), nullable=True),
    sa.Column('positive_x_range_phase', sa.String(length=128), nullable=True),
    sa.Column('negative_x_range_phase', sa.String(length=128), nullable=True),
    sa.Column('result_folder', sa.Text(), nullable=True),
    sa.Column('original_prpd_path', sa.Text(), nullable=True),
    sa.Column('original_tf_path', sa.Text(), nullable=True),
    sa.Column('annotated_image_path', sa.Text(), nullable=True),
    sa.Column('per_image_csv_path', sa.Text(), nullable=True),
    sa.Column('auto_not_measurable_recommended', sa.Boolean(), nullable=True),
    sa.Column('auto_not_measurable_status', sa.String(length=255), nullable=True),
    sa.Column('auto_not_measurable_reason', sa.Text(), nullable=True),
    sa.Column('not_measurable_reason', sa.Text(), nullable=True),
    sa.Column('input_check_status', sa.String(length=16), nullable=True),
    sa.Column('input_has_warning', sa.Boolean(), nullable=False),
    sa.Column('input_warning_count', sa.Integer(), nullable=False),
    sa.Column('input_warnings', sa.Text(), nullable=True),
    sa.Column('user_confirmed_input_warning', sa.Boolean(), nullable=False),
    sa.Column('prpd_filename_check', sa.Boolean(), nullable=True),
    sa.Column('tf_filename_check', sa.Boolean(), nullable=True),
    sa.Column('pair_filename_match', sa.Boolean(), nullable=True),
    sa.Column('plot_frame_detected', sa.Boolean(), nullable=True),
    sa.Column('plot_area_ratio', sa.Float(), nullable=True),
    sa.Column('plot_area_status', sa.String(length=32), nullable=True),
    sa.Column('auto_gap_model_available', sa.Boolean(), nullable=True),
    sa.Column('auto_gap_model_version', sa.String(length=64), nullable=True),
    sa.Column('auto_left_line_pixel', sa.Float(), nullable=True),
    sa.Column('auto_right_line_pixel', sa.Float(), nullable=True),
    sa.Column('rule_based_status', sa.String(length=64), nullable=True),
    sa.Column('gap_line_source', sa.String(length=32), nullable=True),
    sa.Column('manual_adjustment_detected', sa.Boolean(), nullable=True),
    sa.Column('left_line_adjustment_pixel', sa.Float(), nullable=True),
    sa.Column('right_line_adjustment_pixel', sa.Float(), nullable=True),
    sa.Column('cluster_detection_status', sa.String(length=64), nullable=True),
    sa.Column('sanity_check_ran', sa.Boolean(), nullable=False),
    sa.Column('sanity_check_passed', sa.Boolean(), nullable=True),
    sa.Column('sanity_upper_ratio', sa.Float(), nullable=True),
    sa.Column('sanity_lower_ratio', sa.Float(), nullable=True),
    sa.Column('sanity_left_ratio', sa.Float(), nullable=True),
    sa.Column('sanity_right_ratio', sa.Float(), nullable=True),
    sa.Column('prpd_storage_path', sa.Text(), nullable=True),
    sa.Column('tf_storage_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_ai_final_result'), ['ai_final_result'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_case_base_name'), ['case_base_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_severity_by_gap_time'), ['severity_by_gap_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_status'), ['status'], unique=False)

    op.create_table('edit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('case_base_name', sa.String(length=255), nullable=False),
    sa.Column('changed_field', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_history_case_base_name'), ['case_base_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_edit_history_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_history_case_id'))
        batch_op.drop_index(batch_op.f('ix_edit_history_case_base_name'))

    op.drop_table('edit_history')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_status'))
        batch_op.drop_index(batch_op.f('ix_cases_severity_by_gap_time'))
        batch_op.drop_index(batch_op.f('ix_cases_record_id'))
        batch_op.drop_index(batch_op.f('ix_cases_case_base_name'))
        batch_op.drop_index(batch_op.f('ix_cases_batch_id'))
        batch_op.drop_index(batch_op.f('ix_cases_ai_final_result'))

    op.drop_table('cases')
    with op.batch_alter_table('user_thresholds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_thresholds_user_id'))

    op.drop_table('user_thresholds')
    with op.batch_alter_table('trained_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trained_models_status'))
        batch_op.drop_index(batch_op.f('ix_trained_models_owner_id'))

    op.drop_table('trained_models')
    with op.batch_alter_table('calibration_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_presets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_calibration_presets_image_width'))
        batch_op.drop_index(batch_op.f('ix_calibration_presets_image_height'))

    op.drop_table('calibration_presets')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_owner_id'))
        batch_op.drop_index(batch_op.f('ix_batches_batch_key'))

    op.drop_table('batches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_log_username'))

    op.drop_table('usage_log')
    # ### end Alembic commands ###
