"""Export column orders, copied verbatim from the Colab artefacts.

MASTER_SUMMARY_COLUMNS is the header of
    CMD_FINAL_RESULTS_TOPCLASS_RULE_V2_20260523/final_summary.csv
(73 columns) and is the canonical record shape for this system.

PROTOTYPE_EXCEL_COLUMNS is the 41-column sheet the PD_Insight prototype
exported (spec section 7.1). Both are offered from the Export Center.
"""

from __future__ import annotations

MASTER_SUMMARY_COLUMNS: list[str] = [
    "record_id",
    "defect_id",
    "defect_name",
    "case_folder",
    "case_base_name",
    "prpd_filename",
    "tf_filename",
    "source_prpd_path",
    "source_tf_path",
    "ai_mode",
    "ai_input_mode",
    "ai_model_used",
    "ai_model_path",
    "ai_top_class",
    "ai_top_score_percent",
    "ai_final_result",
    "ai_final_score_percent",
    "ai_status",
    "ai_high_conf_count",
    "ai_non_identified_percent",
    "ai_decision_rule",
    "ai_threshold_percent",
    "ai_confidence_corona",
    "ai_confidence_surface",
    "ai_confidence_internal",
    "pd_rule_class",
    "pd_selection_rule",
    "is_strong_pd_rule",
    "suggested_pd_source_type",
    "confirmed_pd_source_type",
    "image_width",
    "image_height",
    "default_size_match",
    "calibration_mode",
    "auto_calibration_status",
    "calibration_source",
    "calibration_preset_loaded",
    "calibration_preset_path",
    "x_left_0deg",
    "x_right_360deg",
    "y_top_plot",
    "y_bottom_plot",
    "auto_gap_status",
    "review_status",
    "reviewer_name",
    "reviewer_role",
    "review_note",
    "created_time",
    "updated_time",
    "left_line_pixel",
    "right_line_pixel",
    "left_phase_deg",
    "right_phase_deg",
    "gap_angle_deg",
    "gap_time_ms",
    "gap_time_band",
    "severity_by_gap_time",
    "gap_measurement_status",
    "remark",
    "detected_case",
    "positive_x_range_pixel",
    "negative_x_range_pixel",
    "positive_x_range_phase",
    "negative_x_range_phase",
    "result_folder",
    "original_prpd_path",
    "original_tf_path",
    "annotated_image_path",
    "per_image_csv_path",
    "auto_not_measurable_recommended",
    "auto_not_measurable_status",
    "auto_not_measurable_reason",
    "not_measurable_reason",
]

# Column order of the PD_Insight prototype's master workbook (spec 7.1).
PROTOTYPE_EXCEL_COLUMNS: list[str] = [
    "record_id",
    "case_base_name",
    "prpd_filename",
    "tf_filename",
    "image_preview",
    "annotated_image_path",
    "ai_confidence_corona",
    "ai_confidence_surface",
    "ai_confidence_internal",
    "ai_top_class",
    "ai_top_score_percent",
    "ai_final_result",
    "ai_final_score_percent",
    "ai_status",
    "ai_decision_rule",
    "ai_threshold_percent",
    "suggested_pd_source_type",
    "confirmed_pd_source_type",
    "gap_angle_deg",
    "gap_time_ms",
    "gap_time_band",
    "severity_by_gap_time",
    "final_left_line_pixel",
    "final_right_line_pixel",
    "left_phase_deg",
    "right_phase_deg",
    "gap_measurement_status",
    "not_measurable_reason",
    "review_status",
    "reviewer_name",
    "reviewer_role",
    "review_note",
    "is_abstract_case",
    "abstract_defect_id",
    "abstract_defect_name",
    "result_folder",
    "original_prpd_path",
    "original_tf_path",
    "per_image_csv_path",
    "created_time",
    "updated_time",
]

EDIT_HISTORY_COLUMNS: list[str] = [
    "timestamp",
    "case_base_name",
    "changed_field",
    "old_value",
    "new_value",
    "changed_by",
]

FINAL_SUMMARY_SHORT_COLUMNS: list[str] = [
    "case_base_name",
    "ai_final_result",
    "confirmed_pd_source_type",
    "severity_by_gap_time",
    "review_status",
    "reviewer_name",
    "updated_time",
]

assert len(MASTER_SUMMARY_COLUMNS) == 73
assert len(PROTOTYPE_EXCEL_COLUMNS) == 41
